vich_uploader:
    db_driver: orm

    mappings:
        news_images:
            uri_prefix: /images/news
            upload_destination: '%kernel.project_dir%/public/images/news'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
        information_images:
            uri_prefix: /images/information
            upload_destination: '%kernel.project_dir%/public/images/information'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
        standby_media:
            uri_prefix: /media/standby
            upload_destination: '%kernel.project_dir%/public/media/standby'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
